[package]
name = "rust_htmx"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
axum = "0.7.4"
askama = "0.12.1"
tokio = { version = "1", features = ["full"] }
